# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 761b5137eaacf895b1867b57cb9400d9bfe6086aab47fdd4965eb0822ccba41761d20faca23bd27697b031341067db94f5286eaee9944372e717df4b902994a2

test:
  secret_key_base: 1734c27266d19bd8dec36eb1ef88ec191ef3c93611fb3f7944e090777008316d8f892c19d152f0469cba8de7227fa21591e02cab710bc18ff038d4001efe0f3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
